application.version: ${version}

logging:
  logback:
    rollingpolicy:
      max-history: 7
      total-size-cap: 1GB
      clean-history-on-start: true
      max-file-size: 10MB
  file:
    name: \${komga.config-dir}/logs/komga.log
  level:
    org.apache.activemq.audit: WARN

komga:
  libraries-scan-cron: "0 0 */8 * * ?"
  libraries-scan-directory-exclusions:
    - "#recycle"  # Synology
    - "@eaDir"    # Synology
    - "@Recycle"  # Qnap
  database:
    file: \${komga.config-dir}/database.sqlite
  lucene:
    data-directory: \${komga.config-dir}/lucene
  session-timeout: 7d
  config-dir: \${user.home}/.komga
  storageType: local


spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    mixed: true
    placeholders:
      library-file-hashing: \${komga.file-hashing:true}
  thymeleaf:
    prefix: classpath:/public/
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 1h
  artemis:
    broker-url: tcp://localhost:18515
    embedded:
      persistent: true
      data-directory: \${komga.config-dir}/artemis
  web:
    resources:
      add-mappings: false
  jackson:
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true
  config:
    import:
      - "optional:file:\${komga.config-dir}/application.yml"
      - "optional:file:\${komga.config-dir}/application.yaml"
      - "optional:file:\${komga.config-dir}/application.properties"

server:
  servlet.session.timeout: 7d
  forward-headers-strategy: framework
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      roles: ADMIN
      show-details: when_authorized
    shutdown:
      enabled: true
  metrics:
    export:
      influx:
        enabled: false
      simple:
        enabled: true
        step: 24h
  info:
    java:
      enabled: true
    os:
      enabled: true
springdoc:
  group-configs:
    - group: REST API
      paths-to-match: /api/**
    - group: OPDS
      paths-to-match: /opds/**
  swagger-ui:
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
